version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: migration
      POSTGRES_PASSWORD: "bnDc2BatCcy3aByOS2e7YQ4YV0CNzHqE"
    volumes:
      - migration_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "ohw6a3m5s6UfAwPwngxknhF37agNmDo1"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  migration_data:
