version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dorado_dumpster
      POSTGRES_PASSWORD: "wiRZCr2O8P6_a-FiHICehZ-dj7sCq5BH"
    volumes:
      - dorado_dumpster_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "h6kWDN4l1G0iCpKVDsnARW0iU5-sWgzx"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  dorado_dumpster_data:
